config/routes.rb
Android4yeWeb::Application.routes.draw do
    # devise
  devise_for :users, :path => 'account',
                     :controllers => {
                       :sessions => :"sessions"
                     }
end

Android4yeWeb::Application.routes.draw do
  namespace :api do
    get "/user_info" => 'index#user_info'

    resources :questions do
      member do
        post :do_answer
      end
    end

    resources :knowledge_nets do
      member do
        get :exp_info
        get :concepts
      end
      collection do
        get :list
      end

      resources :knowledge_sets do
        member do
          get :concepts
        end
      end
      resources :knowledge_nodes do
        member do
          get :test_success
          get :concepts 
        end
      end
      
    end
    
    get "/knowledge_nets/:net_id/knowledge_nodes/:id/get_random_question" => "knowledge_nets#random_question"
    get "/knowledge_nets/:net_id/knowledge_nodes/:id/get_random_questions" => "knowledge_nets#random_questions"
    get "/user/profile" => 'index#user_profile'
                       
    resources :concepts do
      member do
        get :learned_node_random_questions
      end
    end
  end
end

Android4yeWeb::Application.routes.draw do
  namespace :admin do
    resources :questions do
      collection do
        get :list
        get :net
        get :set
        get :node
        get :concepts
        get :edit_concept
        put :update_concept
        delete :destroy_concept
        post :create_concept
      end
    end

    root :to => 'index#index'
    resources :image_datas
    get "/debug" => "debug#index"
    get "/debug/knowledge_nets/:net_id" => "debug#debug_net"
    get "/debug/knowledge_nets/:net_id/knowledge_sets/:set_id" => "debug#debug_set"
  end
end

Android4yeWeb::Application.routes.draw do
  mount UpdaterApp => "/update"
end

app/models/question.rb
# coding: utf-8
require "question_content_parser"

class Question
  include Mongoid::Document
  include Mongoid::Timestamps

	SINGLE_CHOICE   = "single_choice"
	MULTIPLE_CHOICE = "multiple_choices"
	TRUE_FALSE      = "true_false"
  FILL            = "fill"

  STANDARD_FORMAT = "standard_format"
  MARKDOWN_FORMAT = "markdown_format"

  field :knowledge_node_id, :type => String
  field :knowledge_net_id,  :type => String
  field :kind,              :type => String
  field :content,           :type => String
  field :content_type,      :type => String
  field :choices,           :type => Array
  field :difficulty,        :type => String
  field :answer,            :type => String

  has_and_belongs_to_many :concepts
  
  validates :kind, :presence => true
  
  def is_single_choice?
    self.kind == SINGLE_CHOICE
  end

  def is_multiple_choices?
    self.kind == MULTIPLE_CHOICE
  end

  def is_true_false?
    self.kind == TRUE_FALSE
  end

  def is_fill?
    self.kind == FILL
  end

  def check_answer(input)
    self.answer == input
  end

  def get_kind_str
    case self.kind
    when MULTIPLE_CHOICE then "多选题"
    when TRUE_FALSE then "判断题"
    when FILL then "填空题"
    else "单选题"
    end
  end

  def net
    KnowledgeSpaceNetLib::KnowledgeNet.find(self.knowledge_net_id)
  end

  def set
    self.node.set
  end

  def node
    self.net.find_node_by_id(self.knowledge_node_id)
  end

  def make_content
    return MarkdownQuestionContentParser.new(content).parse if MARKDOWN_FORMAT == content_type
    StandardQuestionContentParser.new(content).output
  end

  def make_choices
    choices.map do |choice|
      if MARKDOWN_FORMAT == content_type
        MarkdownQuestionContentParser.new(choice).parse 
      else
        StandardQuestionContentParser.new(choice).output
      end
    end
  end
  
  def as_json(options={})
    json = super(options.merge :except => [:_id])
    json[:content] = make_content
    json[:id] = _id
    json
  end

  def self.from_json(json)
    self.new(JSON.parse(json))
  end

  def self.from_yaml(yaml)
    self.new(YAML.load(yaml))
  end

  def self.all_questions_for_node_id(net_id, node_id)
    Question.where(:knowledge_net_id => net_id, :knowledge_node_id => node_id)
  end

  def self.random_question_for_node_id(net_id, node_id, except_ids=[])
    result = self.random_questions_for_node_id(net_id, node_id, 1, except_ids)
    result ? result.first : result
  end

  def self.random_questions_for_node_id(net_id, node_id, number=1, except_ids=[])
    questions = all_questions_for_node_id(net_id, node_id).where(:_id.nin => except_ids)
    count = questions.count
    return if count == 0

    offsets = (0..(count - 1)).sort_by{rand}.slice(0, number).collect
    offsets.map {|offset| questions.skip(offset).first}
  end

  def self.formats
    [["标准录入格式", STANDARD_FORMAT], ["Markdown格式", MARKDOWN_FORMAT]]
  end

  def self.kinds
    [["单选题", SINGLE_CHOICE], ["多选题", MULTIPLE_CHOICE], ["判断题", TRUE_FALSE], ["填空题", FILL]]
  end

  include Concept::QuestionMethods
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::ApplicationController
  before_filter :is_admin
  def is_admin
    if !current_user.is_admin?
      render :status => 401, :text => 401
    end
  end

  def index
    @nets = KnowledgeSpaceNetLib::KnowledgeNet.all
  end

  def net
    @net = KnowledgeSpaceNetLib::KnowledgeNet.find(params[:id])
  end
  
  def set
    @net = KnowledgeSpaceNetLib::KnowledgeNet.find(params[:net_id])
    @set = @net.find_set_by_id(params[:id])
  end

  def node
    @net = KnowledgeSpaceNetLib::KnowledgeNet.find(params[:net_id])
    @node = @net.find_node_by_id(params[:id])
    @questions = Question.where(:knowledge_node_id => @node.id, :knowledge_net_id => @net.id)
  end

  def concepts
    @net = KnowledgeSpaceNetLib::KnowledgeNet.find(params[:net_id])
    @node = @net.find_node_by_id(params[:id])
    @concepts = Concept.where(:knowledge_node_id => @node.id, :knowledge_net_id => @net.id)
    @concept = Concept.new(:knowledge_node_id => @node.id, :knowledge_net_id => @net.id)
  end

  def edit_concept
    @concept = Concept.find(params[:id])
    @net = KnowledgeSpaceNetLib::KnowledgeNet.find(@concept.knowledge_net_id)
    @node = @net.find_node_by_id(@concept.knowledge_node_id)
    @update_url = update_concept_admin_questions_path(:id => @concept.id)
  end
  
  def update_concept
    concept = Concept.find(params[:id])
    concept.update_attributes(params[:concept])
    return redirect_to concepts_admin_questions_path(:id => concept.knowledge_node_id, :net_id => concept.knowledge_net_id)

  end
  
  def create_concept
    @concept = Concept.create(params[:concept])
    redirect_to :back
  end

  def destroy_concept
    @concept = Concept.find(params[:id])
    @concept.destroy if @concept
    redirect_to :back
  end
  
  def list
    @questions = Question.all
  end

  def new
    @net = KnowledgeSpaceNetLib::KnowledgeNet.find(params[:net_id])
    @question = Question.new
    @question.knowledge_net_id = @net.id
    @node = @net.find_node_by_id(params[:node_id])
    @question.knowledge_node_id = @node.id
  end

  def edit
    @question = Question.find(params[:id])
    @net = @question.net
    @node = @question.node
  end

  def create
    @question = Question.new(params[:question])
    @question.choices = nil if Question::TRUE_FALSE == params[:question][:kind]
    @question.save
    redirect_to node_admin_questions_path(
      :id     => @question.knowledge_node_id,
      :net_id => @question.knowledge_net_id
    )
  end

  def update
    @question = Question.find(params[:id])
    @question.update_attributes(params[:question])
    @question.choices = nil if Question::TRUE_FALSE == params[:question][:kind]
    @question.concept_ids = [] if params[:question][:concept_ids].blank?
    @question.save
    redirect_to :back
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy if @question
    redirect_to node_admin_questions_path(:id => @question.knowledge_node_id, :net_id => @question.knowledge_net_id)
  end
end

app/controllers/api/questions_controller.rb
class Api::QuestionsController < ApplicationController
  def do_answer
    @question = Question.find(params[:id])
    case params[:answer]
      when "true"
        @question.do_correct(current_user)
      when "false"
        @question.do_error(current_user)
    end

    render :text => 200
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :is_admin
  def is_admin
    if !current_user.is_admin?
      render :status => 401, :text => 401
    end
  end

  def index
    @nets = KnowledgeSpaceNetLib::KnowledgeNet.all
  end

  def net
    @net = KnowledgeSpaceNetLib::KnowledgeNet.find(params[:id])
  end
  
  def set
    @net = KnowledgeSpaceNetLib::KnowledgeNet.find(params[:net_id])
    @set = @net.find_set_by_id(params[:id])
  end

  def node
    @net = KnowledgeSpaceNetLib::KnowledgeNet.find(params[:net_id])
    @node = @net.find_node_by_id(params[:id])
    @questions = Question.where(:knowledge_node_id => @node.id, :knowledge_net_id => @net.id)
  end

  def concepts
    @net = KnowledgeSpaceNetLib::KnowledgeNet.find(params[:net_id])
    @node = @net.find_node_by_id(params[:id])
    @concepts = Concept.where(:knowledge_node_id => @node.id, :knowledge_net_id => @net.id)
    @concept = Concept.new(:knowledge_node_id => @node.id, :knowledge_net_id => @net.id)
  end

  def edit_concept
    @concept = Concept.find(params[:id])
    @net = KnowledgeSpaceNetLib::KnowledgeNet.find(@concept.knowledge_net_id)
    @node = @net.find_node_by_id(@concept.knowledge_node_id)
    @update_url = update_concept_questions_path(:id => @concept.id)
  end
  
  def update_concept
    concept = Concept.find(params[:id])
    concept.update_attributes(params[:concept])
    return redirect_to concepts_questions_path(:id => concept.knowledge_node_id, :net_id => concept.knowledge_net_id)

  end
  
  def create_concept
    @concept = Concept.create(params[:concept])
    redirect_to :back
  end

  def destroy_concept
    @concept = Concept.find(params[:id])
    @concept.destroy if @concept
    redirect_to :back
  end
  
  def list
    @questions = Question.all
  end

  def new
    @net = KnowledgeSpaceNetLib::KnowledgeNet.find(params[:net_id])
    @question = Question.new
    @question.knowledge_net_id = @net.id
    @node = @net.find_node_by_id(params[:node_id])
    @question.knowledge_node_id = @node.id
  end

  def edit
    @question = Question.find(params[:id])
    @net = @question.net
    @node = @question.node
  end

  def create
    @question = Question.new(params[:question])
    @question.choices = nil if Question::TRUE_FALSE == params[:question][:kind]
    @question.save
    redirect_to node_questions_path(
      :id     => @question.knowledge_node_id,
      :net_id => @question.knowledge_net_id
    )
  end

  def update
    @question = Question.find(params[:id])
    @question.update_attributes(params[:question])
    @question.choices = nil if Question::TRUE_FALSE == params[:question][:kind]
    @question.concept_ids = [] if params[:question][:concept_ids].blank?
    @question.save
    redirect_to :back
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy if @question
    redirect_to :action => :index
  end
end

app/views/admin/questions/_concept_form.html.haml
- url = @update_url ? @update_url : create_concept_admin_questions_path
= form_for @concept, :url => url do |f|
  = f.hidden_field :knowledge_node_id
  = f.hidden_field :knowledge_net_id
  .control
    = f.label :name, "概念"
    = f.text_field :name

  .control
    = f.label :desc, "描述"
    = f.text_area :desc

  .control
    = f.submit "提交"

app/views/admin/questions/_form.html.haml
.widget.choice.text-input.template{:style => "display:none;"}
  = text_area_tag "question[choices][]", nil, :rows => 2, :cols => 32
  = link_to "删除", "javascript:;", :style => "vertical-align:top;", :class => "remove-choice"
= form_for [:admin, @question] do |f|
  = f.hidden_field :knowledge_net_id

  .control
    = f.label :knowledge_node_id, "知识点"
    - opts = @node.set.nodes.map {|node| [node.name, node.id]}
    = f.select :knowledge_node_id, options_for_select(opts, [@node.name, @node.id])

  .control
    = f.label :concepts, "相关概念"
    .widgets
      - KnowledgeNodeAdapter.new(@node).available_concepts.each do |concept|
        .widget
          = label_tag do
            - checked = @question.concepts.include?(concept)
            = check_box_tag "question[concept_ids][]", concept.id, checked
            = concept.name

  .control
    = f.label :content_type, "内容录入语法"
    - format = @question.content_type ? Question.formats.select {|x| @question.content_type == x[1]}[0] : Question.formats[0]
    - format_options = options_for_select(Question.formats, format)
    = f.select :content_type, format_options

  .control
    = f.label :kind, "问题类型"
    - kind_options = Question.kinds
    = f.select :kind, Question.kinds, :include_blank => true

  .control
    = f.label :content, "内容"
    = f.text_area :content, :rows => 20, :cols => 64

  .control
    = f.label :choices, "选项"
    .ops
      = link_to "添加", "javascript:;", :class => "add-choice"
    .widgets{:style => @question.choices ? "" : "display:none;"}
      - if @question.choices
        - @question.choices.each do |choice|
          .widget.choice.text-input
            = text_area_tag "question[choices][]", choice, :rows => 2, :cols => 32
            = link_to "删除", "javascript:;", :style => "vertical-align:top;", :class => "remove-choice"        

  .control
    = f.label :answer, "答案"
    = f.text_field :answer

  .control
    = f.submit "提交"

app/views/admin/questions/concepts.html.haml
.page-question-set
  %h1.title #{@node.name} - 概念管理
  .nav
    = link_to "首页", admin_questions_path
    >
    = link_to @net.name, net_admin_questions_path(:id => @net.id)
    >
    = link_to @node.set.name, set_admin_questions_path(:id => @node.set.id, :net_id => @net.id)
    >
    = link_to "#{@node.name}-概念管理", concepts_admin_questions_path(:id => @node.id, :net_id => @net.id), :class => "current"
  .items.concepts
    - @concepts.each do |concept|
      .item
        .title
          = concept.name 
          .ops
            - edit = link_to "编辑", edit_concept_admin_questions_path(:id => concept.id)
            - delete = link_to "删除", destroy_concept_admin_questions_path(:id => concept.id), :method => :delete, :confirm => "确定删除?"
            = edit + delete
        .desc= concept.desc

  .new-concept.form
    = render "concept_form"

app/views/admin/questions/edit.html.haml
.page-question-form.edit
  %h1.title 编辑测试题
  .nav
    = link_to "首页", admin_questions_path
    >
    = link_to @net.name, net_admin_questions_path(:id => @net.id)
    >
    = link_to @node.set.name, set_admin_questions_path(:id => @node.set.id, :net_id => @net.id)
    >
    = link_to @node.name, node_admin_questions_path(:id => @node.id, :net_id => @net.id)
    >
    = link_to "编辑测试题", edit_admin_question_path(:id => @question.id), :class => "current"
  .question-form.form
    = render "form"

app/views/admin/questions/edit_concept.html.haml
.page-edit-concept
  %h1.title 编辑概念 #{@concept.name}
  .nav
    = link_to "首页", admin_questions_path
    >
    = link_to @net.name, net_admin_questions_path(:id => @net.id)
    >
    = link_to @node.set.name, set_admin_questions_path(:id => @node.set.id, :net_id => @net.id)
    >
    = link_to "#{@node.name}-概念管理", concepts_admin_questions_path(:id => @node.id, :net_id => @net.id)
    >
    = link_to "#{@concept.name}-编辑", edit_concept_admin_questions_path(:id => @concept.id), :class => "current"
  .edit-concept.form
    = render "concept_form"

app/views/admin/questions/index.html.haml
.page-question-nets
  %h1.title 知识领域列表
  .nav
    = link_to "首页", admin_questions_path, :class => "current"
  .items
    - @nets.each do |net|
      .knowledge-net.item
        .title
          = net.name
          .ops
            = link_to "打开", net_admin_questions_path(:id => net.id)

app/views/admin/questions/list.html.haml
.page-questions
  .header
    %h1 测试题列表
  .question-list
    - @questions.each do |question|
      .question
        .content= question.content
        .ops
          = link_to "编辑", edit_admin_question_path(question)
          = link_to "删除", admin_question_path(question), :method => :delete

app/views/admin/questions/net.html.haml
.page-question-net
  %h1.title #{@net.name} - 知识单元列表
  .nav
    = link_to "首页", admin_questions_path
    >
    = link_to @net.name, net_admin_questions_path(:id => @net.id), :class => "current"
  .items
    - @net.sets.each do |set|
      .knowledge-set.item
        .title
          = set.name
          .ops
            = link_to "打开", set_admin_questions_path(:id => set.id, :net_id => @net.id)

app/views/admin/questions/new.html.haml
.page-question-form
  %h1.title 新建测试题
  .nav
    = link_to "首页", admin_questions_path
    >
    = link_to @net.name, net_admin_questions_path(:id => @net.id)
    >
    = link_to @node.set.name, set_admin_questions_path(:id => @node.set.id, :net_id => @net.id)
    >
    = link_to @node.name, node_admin_questions_path(:id => @node.id, :net_id => @net.id)
    >
    = link_to "新建测试题", new_admin_question_path(:id => @node.id, :net_id => @net.id), :class => "current"
  .question-form.form
    = render "form"

app/views/admin/questions/node.html.haml
.page-question-node
  %h1.title #{@node.name} - 测试题管理
  .nav
    = link_to "首页", admin_questions_path
    >
    = link_to @net.name, net_admin_questions_path(:id => @net.id)
    >
    = link_to @node.set.name, set_admin_questions_path(:id => @node.set.id, :net_id => @net.id)
    >
    = link_to @node.name, node_admin_questions_path(:id => @node.id, :net_id => @net.id), :class => "current"
  = link_to "新建", new_admin_question_path(:node_id => @node.id, :net_id => @net.id), :class => "new"
  .question-list.items
    - @questions.each do |question|
      .item.question
        .title
          = question.content
          .ops
            - edit = link_to "编辑", edit_admin_question_path(question)
            - remove = link_to "删除", admin_question_path(question), :method => :delete, :confirm => "确认删除?"
            = edit + remove

app/views/admin/questions/set.html.haml
.page-question-set
  %h1.title #{@set.name} - 知识节点列表
  .nav
    = link_to "首页", admin_questions_path
    >
    = link_to @net.name, net_admin_questions_path(:id => @net.id)
    >
    = link_to @set.name, set_admin_questions_path(:id => @set.id, :net_id => @net.id), :class => "current"
  .items.nodes
    - @set.nodes.each do |node|
      .item
        .title
          = node.name
          .ops
            - open = link_to "打开", node_admin_questions_path(:id => node.id, :net_id => @net.id)
            - concept = link_to "相关概念管理", concepts_admin_questions_path(:id => node.id, :net_id => @net.id)
            = open + concept